import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class RecipeService {
  recipes = [
    { id: 4400, name: 'Pasteles De Yuca As Made By Iván Emilio' },
    { id: 4401, name: 'Guatemalan Paches As Made By Erwin Perez' },
    {
      id: 4402,
      name: 'Dominican Pasteles En Hoja As Made By Julissa Calderon',
    },
    { id: 4404, name: 'Slow Cooker Vegan Butternut Squash Mac' },
    { id: 4405, name: 'Seared Salmon With Smoky Squash Salad' },
    { id: 4406, name: 'One-Pan Maple Rosemary Chicken' },
    { id: 4407, name: 'Family Arepas As Made By Cesar' },
    { id: 4409, name: 'Mexican Sopes' },
    { id: 4410, name: "Mama Guilla's Sancocho" },
    { id: 4411, name: 'Mushroom, Spinach & Sausage Spaghetti' },
    { id: 4413, name: 'Halloween Feet Loaf' },
    { id: 4414, name: '30-Minute Pizza Party Boats' },
    { id: 4416, name: 'Giant Caramel Candy Bar Cake' },
    { id: 4417, name: 'Cauliflower Gnocchi' },
    { id: 4418, name: 'Crispie Voter Ballot Box By Bliss & Baker' },
    { id: 4419, name: '20-Minute One-Pan Pizza' },
    { id: 4420, name: 'Takeout-Style Veggie Egg Rolls' },
    { id: 4421, name: 'Takeout-Style Shrimp & Pork Egg Rolls' },
    { id: 4422, name: 'Halloween Party Punch' },
    {
      id: 4423,
      name: 'Nicaraguan Vigorón And Tajadas As Made By Cat Alvarado',
    },
    { id: 4424, name: 'Salvadoran Pupusas As Made By Curly And His Abuelita' },
    { id: 4425, name: 'Pumpkin Bread Ring With Maple Cream Cheese Filling' },
    { id: 4426, name: 'Queso Hash Brown Breakfast Ring' },
    { id: 4427, name: 'Chicken Curry Naan Bowls' },
    { id: 4430, name: "Bean And Cheese Toaster 'Quesadilla'" },
    { id: 4431, name: "Buffalo Chicken Toaster 'Quesadilla'" },
    { id: 4432, name: "Turkey Pesto Toaster 'Quesadilla'" },
    {
      id: 4433,
      name: "Strawberry Banana Chocolate Hazelnut Toaster 'Quesadilla'",
    },
    { id: 4434, name: 'Sugar Spice Pear Galette' },
    { id: 4435, name: 'Easy Chicken Curry With Kanchan Koya' },
    { id: 4436, name: 'Halloween Bundt Cake' },
    { id: 4437, name: 'Vegan Pumpkin Cheesecake Bars' },
    { id: 4438, name: 'Cranberry Fruit Rollers' },
    { id: 4439, name: 'Pumpkin Spice Fruit Rollers' },
    { id: 4440, name: 'Grape Fruit Rollers' },
    { id: 4442, name: 'Java Chip Caffeinated Smoothie' },
    { id: 4443, name: 'Peanut Butter Banana Caffeinated Smoothie' },
    { id: 4444, name: 'Thai Iced Tea Caffeinated Smoothie' },
    { id: 4445, name: 'Vanilla Matcha Caffeinated Smoothie' },
    { id: 4446, name: 'Vegan Red Velvet Cupcakes With Cream Cheese Frosting' },
    { id: 4447, name: 'Vegan Chocolate Cupcakes With Chocolate Frosting' },
    { id: 4448, name: 'Vegan Vanilla Cupcakes With Rainbow Sprinkle Frosting' },
    { id: 4449, name: 'Vegan Pumpkin Cupcakes With Maple Frosting' },
    { id: 4450, name: 'Tom Yum Soup' },
    { id: 4451, name: 'Brown Butter Sage Pierogi' },
    { id: 4452, name: '4-Flavor Giant Sheet Pan Breakfast Sandwich' },
    { id: 4453, name: 'Sweet Potato Breakfast Cups' },
    { id: 4454, name: "Shepherd's Pie" },
    { id: 4455, name: 'Baked Brie In A Bread Bowl' },
    { id: 4456, name: 'Voting Party Cookies' },
    { id: 4457, name: 'Simple Quick-Pickled Veggies' },
    { id: 4458, name: 'Pumpkin Spice Bites' },
    { id: 4459, name: 'Apple Pie Bites' },
    { id: 4460, name: 'Pecan Cranberry Bites' },
    { id: 4462, name: 'Pumpkin Chili Cheese Dip' },
    { id: 4463, name: 'Seeded Pumpkin Breakfast Bread' },
    { id: 4464, name: 'Mulled Wine' },
    { id: 4465, name: 'Hot Toddy' },
    { id: 4466, name: 'Spiked Apple Cider' },
    { id: 4467, name: 'Spiked Hot Chocolate' },
    { id: 4468, name: "Chrissy Teigen's Jalapeño-Cheddar Corn Pudding" },
    { id: 4469, name: 'Award-Winning Cuban Sandwich By El Cochinito' },
    { id: 4470, name: 'Baked Butternut Squash “Risotto”' },
    { id: 4471, name: 'Holiday Sheet Pan Cheesecake Bars' },
    { id: 4472, name: 'Maple Hazelnut Squash And Sausage Stuffing' },
    { id: 4473, name: 'Churro Cheesecake' },
    { id: 4475, name: 'One Pot Vegan Eggplant Lasagna' },
    { id: 4476, name: 'Turkey Roulade' },
    { id: 4477, name: 'Salted Caramel Apple Pie' },
    { id: 4478, name: 'Cheddar-Crusted & Bacon Broccoli Quiche' },
    { id: 4479, name: 'Rainbow Fall Slaw With Tahini Poppy Seed Dressing' },
    { id: 4480, name: 'Classic Coq Au Vin' },
    { id: 4481, name: 'Butternut Squash Sage Pull-Apart Bread' },
    { id: 4484, name: 'Bleeding Vampire Drink' },
    { id: 4487, name: 'Spider Deviled Eggs' },
    { id: 4488, name: 'Skull Candy Apple' },
    { id: 4489, name: 'Homemade Chimichurri Sauce' },
    { id: 4491, name: 'Top Chef Junior Szechuan Lamb Burger' },
    { id: 4492, name: 'Top Chef Junior Falafel Burger' },
    { id: 4493, name: 'Top Chef Junior Citrus Salmon Burger' },
    { id: 4494, name: 'Cinnamon Apple Quinoa Skillet Bake' },
    { id: 4495, name: 'Roasted Delicata Squash And Farro Salad' },
    { id: 4496, name: 'Healthy Veggie Curry With Garlic Naan' },
    {
      id: 4497,
      name: 'Pan-Fried Shrimp Cakes With Arugula And Watercress Salad',
    },
    { id: 4498, name: 'Dairy-Free Green Bean Casserole' },
    { id: 4499, name: '“Cheesy” Scalloped Potatoes' },
    { id: 4500, name: 'Crispy Fish Tacos' },
    { id: 4501, name: 'Dairy-Free Vegetarian Stroganoff' },
    { id: 4502, name: 'Apple Cider' },
    { id: 4503, name: 'Apple Cider Cupcakes' },
    { id: 4504, name: 'Chai-Spiced Plum Polenta Cake' },
    { id: 4505, name: 'Leftover Halloween Candy-Bottom Cheesecake' },
    { id: 4506, name: 'One-Pan Cider-Braised Pork Chops' },
    { id: 4507, name: 'Coconut Broth Clams' },
    { id: 4508, name: 'Stuffing Vs. Dressing' },
    { id: 4509, name: 'Pumpkin Seed Pesto & Roasted Pumpkin' },
    { id: 4510, name: 'Matcha Latte' },
    { id: 4511, name: 'Hibiscus Latte' },
    { id: 4512, name: 'Lavender London Fog' },
    { id: 4513, name: 'Lavender Latte' },
    { id: 4514, name: 'Piña Colada Cupcakes' },
    { id: 4515, name: 'Dessert Pakoras' },
    { id: 4516, name: 'Vegetable Gratin 3 Ways' },
    { id: 4518, name: 'Pie Crust' },
    { id: 4519, name: 'Pumpkin Pie: Roasted Can' },
    { id: 4520, name: 'Fresh Pumpkin Pie' },
    { id: 4521, name: 'Apple Pie (Macerated)' },
    { id: 4523, name: 'Cranberry Sauce Jello Shots' },
    { id: 4524, name: 'Ultimate Green Bean Casserole' },
    { id: 4526, name: 'Hearty White Bean Stew' },
    { id: 4527, name: 'Vegan Stuffing' },
    { id: 4528, name: 'Vegan Pumpkin Cheesecake' },
    { id: 4529, name: "Giant Zebra 'Box' Cake" },
    { id: 4530, name: 'Slow-Cooker Collard Greens And Ham Hocks' },
    { id: 4532, name: 'Green Bean Casserole' },
    { id: 4533, name: 'Easy Microwave Stuffing' },
    { id: 4534, name: 'Microwave Creamed Corn' },
    { id: 4535, name: 'Microwave Garlic Mashed Potatoes' },
    { id: 4537, name: 'Herb Sea Salt-Rubbed Chicken Thighs' },
    { id: 4538, name: 'Vegan Sweet Potatoes Au Gratin' },
    { id: 4539, name: 'Shrimp Kale Caesar Salad' },
    { id: 4540, name: 'Keto Bacon Cauliflower “Mac” ‘N’ Cheese' },
    { id: 4541, name: 'Spaghetti And Meatballs' },
    { id: 4543, name: 'Creamiest Mashed Potatoes' },
    { id: 4544, name: 'Light And Fluffy Mashed Potatoes' },
    { id: 4545, name: 'Creamy And Decadent Mashed Potatoes' },
    { id: 4546, name: 'Chunky, Skin-On Mashed Potatoes' },
    { id: 4547, name: 'Not-Too-Dense Mashed Sweet Potatoes' },
    { id: 4548, name: 'Creamy Chicken Piccata' },
    { id: 4549, name: 'Curried Leftover Pot Pie  ' },
    { id: 4551, name: 'Holiday Seafood Pot  ' },
    { id: 4552, name: 'Cheesy Taquitos (Chequitos)' },
    { id: 4554, name: 'Quick 30-Minute Chicken Pho' },
    { id: 4555, name: 'Keto-Friendly Lasagna Dome' },
    { id: 4556, name: 'Festive Stuffed Acorn Squash' },
    { id: 4557, name: 'Cornmeal Popovers' },
    { id: 4558, name: '7-Layer Steak Sandwich' },
    { id: 4560, name: 'Stuffed Chicken Parmesan' },
    { id: 4561, name: 'Sweet And Savory Sweet Potato Casserole' },
    { id: 4562, name: 'The Ultimate Dinner Rolls' },
    { id: 4563, name: 'Chicken Meatball Soup' },
    { id: 4564, name: 'Caramelized Onion And Spinach Dip' },
    {
      id: 4565,
      name: 'Dijon-Crusted Pork Tenderloin With Honey-Glazed Carrots',
    },
    {
      id: 4566,
      name: 'Cranberry-Poached Pears With Whipped Cream And Shortbread Crumbles',
    },
    { id: 4567, name: 'Thai Tea Pie By Ray Pajar' },
    { id: 4568, name: 'Classic Creamy Cheesecake' },
    { id: 4569, name: 'Aunt Vivian’s Sweet Potato Pie' },
    { id: 4571, name: 'Thanksgiving Leftover Pizza 2 Ways' },
    { id: 4572, name: 'Sweet & Spicy Oven-Fried Chicken' },
    { id: 4573, name: 'Orange Chocolate Cupcake' },
    { id: 4574, name: 'Paprika Shrimp Pasta' },
    { id: 4575, name: 'Blueberry Tapioca Pie' },
    { id: 4576, name: 'Stuffing with Cornbread' },
    { id: 4577, name: 'Apple Sausage Stuffing' },
    { id: 4578, name: 'Kale And Mushroom Stuffing' },
    { id: 4579, name: 'Brioche Stuffing' },
    { id: 4580, name: 'Fudgy Hidden Veggie Brownies' },
    { id: 4581, name: 'Thanksgiving Leftover Sweet Potato Waffles' },
    { id: 4585, name: 'Vegan Ramen' },
    { id: 4586, name: 'Raspberry Mojito' },
    { id: 4587, name: 'Raspberry Ripple Cheesecake' },
    { id: 4588, name: 'Lemon Bundt Cake' },
    { id: 4589, name: 'Herb Salt-Crusted Strip Steak' },
    { id: 4590, name: 'Brussels Sprouts Au Gratin' },
    { id: 4594, name: 'Thai Tofu Collard Wraps' },
    { id: 4598, name: 'Low-Carb Eggplant Parmesan' },
    { id: 4599, name: 'Low-Carb Eggplant Lasagna' },
    { id: 4601, name: 'Nut & Dairy-Free Pumpkin Pie Cheesecake' },
    { id: 4602, name: 'Apple Pie Winter Smoothie' },
    { id: 4603, name: 'Chocolate Coconut Winter Smoothie' },
    { id: 4604, name: 'Sweet Potato Gingerbread Winter Smoothie' },
    { id: 4605, name: 'Pear Chai Winter Smoothie' },
    { id: 4607, name: 'Dairy-Free Chocolate Coconut Espresso Panna Cotta' },
    { id: 4608, name: 'Dairy-Free Coconut Matcha Panna Cotta' },
    { id: 4610, name: 'Rosemary Sweet Potato Muffins' },
    { id: 4611, name: 'Zucchini Cheddar Muffins' },
    { id: 4613, name: 'Hazelnut-Crusted Pear & Brie Tart' },
    { id: 4614, name: 'Winter Citrus Salad' },
    {
      id: 4615,
      name: 'Crispy Rice Chocolate Chip Butterscotch Oatmeal Cookies',
    },
    { id: 4616, name: 'Dutch Oven Jalapeño Cheddar Bread' },
    { id: 4617, name: 'How to Make the Best Sugar Cookies' },
    { id: 4618, name: 'Peppermint Macarons' },
    { id: 4619, name: 'Sherry Mushrooms With Creamy Polenta And Gremolata' },
    { id: 4620, name: 'Light Holiday Eggnog' },
    { id: 4621, name: 'Low-Carb Pad Thai' },
    { id: 4622, name: 'Gin & Tonic Truffles' },
    { id: 4623, name: 'Pineapple Chili Margarita' },
    { id: 4625, name: 'Cheese-Stuffed Mushroom Burger' },
    { id: 4626, name: 'Garlic And Herb-Marinated Rack Of Lamb' },
    { id: 4628, name: 'Rice Cooker Asian Chicken Rice' },
    { id: 4629, name: 'Dairy-Free Vanilla Bean Panna Cotta' },
    { id: 4630, name: 'Dairy-Free Pumpkin Spice Panna Cotta' },
    { id: 4631, name: 'Roasted Cauliflower And Curry Soup' },
    { id: 4632, name: 'Mochi Sesame Balls' },
    { id: 4633, name: 'Chocolate And Chestnut Mochi' },
    {
      id: 4634,
      name: 'Jewish Strawberry Jam And Chocolate Chip Mandelbrot As Made By Danielle Warren',
    },
    { id: 4635, name: 'Classic Meat Lover’s Calzones' },
    { id: 4636, name: 'Chocolate Coconut Almond Balls' },
    { id: 4637, name: 'High-Protein Gingerbread Pancakes' },
    { id: 4638, name: 'Soy-Braised Short Ribs With Shiitakes' },
    { id: 4639, name: 'Chicken Cordon Bleu Lasagna' },
    { id: 4640, name: 'Prime Rib' },
    { id: 4641, name: 'Butter Cookies' },
    {
      id: 4643,
      name: 'How To Decorate Shortbread Holiday Cut-Out Cookies With Royal Icing',
    },
    { id: 4644, name: 'Creamy Broccoli Soup' },
    { id: 4645, name: 'Cranberry Sauce Smoothie' },
    { id: 4646, name: 'Corn And Zucchini Cakes' },
    { id: 4647, name: 'Sweet Potato Breakfast Bars ' },
    { id: 4648, name: 'Speculoos Cookie Butter-Stuffed Snickerdoodles' },
    { id: 4649, name: 'Kahk Eid Cookies' },
    { id: 4650, name: 'Raspberry Poppyseed Linzer Cookies' },
    { id: 4651, name: 'Apple Galette' },
    { id: 4652, name: 'Homemade Eggnog' },
    { id: 4653, name: 'Eggnog Cookie Dippers' },
    { id: 4654, name: 'Cheesy Bacon Twists' },
    { id: 4655, name: 'Pumpkin Pie Bread Pudding' },
    { id: 4656, name: 'Crunchy California Roll Sushi Bowl' },
    { id: 4657, name: 'Cheesesteak Roll-Ups' },
    { id: 4658, name: 'Yellow Squash Lasagna ' },
    { id: 4659, name: 'Carnitas Salad ' },
    {
      id: 4661,
      name: 'Curry Sticky Rice Stuffed With Short Rib By Chef JJ Johnson',
    },
    { id: 4662, name: 'Baked Pear Crumble' },
    { id: 4663, name: 'Lil’ Merri’s As Made By Elizabeth Belkind' },
    { id: 4664, name: 'Banana Oat Freezer-Prep Smoothie' },
    { id: 4665, name: 'Green Machine Freezer-Prep Smoothie' },
    { id: 4666, name: 'Mixed Berry Freezer-Prep Smoothie' },
    { id: 4667, name: 'Coconut Mango Freezer-Prep Smoothie' },
    { id: 4669, name: 'Marranito Cookies' },
    { id: 4670, name: 'Salted Caramel Coconut Cookies' },
    { id: 4672, name: 'Thai Coconut Vegetable Curry' },
    { id: 4673, name: 'Vegan Snowflake Sugar Cookies' },
    { id: 4674, name: 'Seasoned Salt Blend' },
    { id: 4675, name: 'Fresh Herb Sauce' },
    { id: 4676, name: 'Holiday Vegetable Wellington' },
    { id: 4677, name: 'Roast Chicken' },
    { id: 4678, name: 'Carrot Cake Cookies' },
    { id: 4679, name: 'Peppermint Brownie Cookies' },
    { id: 4680, name: 'Fruitcake Cupcake Holiday Wreath' },
    { id: 4681, name: 'Hot Chocolate Cookie Mugs' },
    { id: 4682, name: 'Chinese Almond Cookies' },
    { id: 4683, name: 'Homemade Lime Seltzer' },
    { id: 4684, name: 'Cherry Vanilla Soda' },
    { id: 4685, name: 'Lemon Basil Soda' },
    { id: 4686, name: 'Matcha Soda' },
    { id: 4687, name: 'Orangesicle Soda' },
    { id: 4688, name: 'Cheska’s Family Fruitcake' },
    { id: 4690, name: 'Swedish Saffron Buns (Lussebullar)' },
    { id: 4691, name: 'Cranberry Almond Cookies' },
    { id: 4692, name: 'Winter Vegetable Chili' },
    { id: 4693, name: 'How to Make Cinnamon Rolls' },
    { id: 4694, name: '4-Ingredient Holiday Truffles' },
    { id: 4695, name: 'New Year’s Eve Champagne Cookies' },
    { id: 4696, name: 'Tofu Turkey' },
    { id: 4697, name: 'Christmas Tree Pull-Apart Bread' },
    { id: 4698, name: 'Baklava' },
    { id: 4699, name: 'Trinidad Black Cake' },
    { id: 4700, name: 'Pasta Alla Norma' },
    { id: 4702, name: 'Spiced White Chocolate Mocha Whoopie Pies' },
    { id: 4703, name: 'Chicken Bibimbap' },
    { id: 4704, name: 'Low-Carb Avocado Chicken Salad' },
    { id: 4705, name: 'Crunchy Chili Chickpeas' },
    { id: 4706, name: 'Cacao Chia Pudding' },
    { id: 4707, name: 'Quick-Roasted Veggie Bowl' },
    { id: 4708, name: 'Roasted Cauliflower Salad' },
    { id: 4709, name: 'Nutrient-Packed Colorful Super Salad' },
    { id: 4710, name: 'Healthy And Hearty Green Super Soup' },
    { id: 4711, name: 'Vegan Tofu Bao Buns With Pickled Vegetables' },
    { id: 4712, name: 'Instant-Pot Short Ribs' },
    { id: 4713, name: 'Slow Cooker Roasted Tomato Basil Soup' },
    { id: 4714, name: 'Seared Shrimp And Avocado Salad' },
    { id: 4717, name: 'Instant Pot Chicken Bone Broth' },
    { id: 4718, name: 'Hidden Heart Strawberry Bundt Cake' },
    {
      id: 4719,
      name: 'Baked Delicata Squash Rings With Honey Mustard Dipping Sauce',
    },
    { id: 4720, name: 'Low-Sugar Apple Tart' },
    { id: 4721, name: 'Cheesy Garlic Pull-Apart Bread' },
    { id: 4722, name: 'Simple Honey Syrup' },
    { id: 4723, name: 'Cranberry Rosemary Herb Soda' },
    { id: 4726, name: 'Honey Lavender Soda' },
    { id: 4727, name: 'Peppermint Hibiscus Tea' },
    { id: 4728, name: 'Cinnamon Orange Black Tea' },
    { id: 4729, name: 'Lemon Ginger Yerba Mate Tea' },
    { id: 4730, name: 'Mulled Sangria' },
    { id: 4731, name: 'Apple Rosé Sangria' },
    { id: 4732, name: 'White Cranberry Sangria' },
    { id: 4733, name: 'Pomegranate Pear Sangria' },
    { id: 4734, name: 'High-Protein Baked Quinoa Bites' },
    { id: 4735, name: 'Easy To Serve Chicken Parmesan Poppers' },
    { id: 4738, name: 'Low-Carb Steak Salad With Dijon Vinaigrette' },
    { id: 4739, name: 'Citrus And Winter Greens Salad' },
    { id: 4741, name: 'Spaghetti Squash Nests' },
    { id: 4743, name: 'Cauliflower Walnut Burritos' },
    { id: 4744, name: 'Mushroom And Kale Burritos' },
    { id: 4745, name: 'Tofu Scramble Breakfast Burrito' },
    { id: 4746, name: 'Sweet Potato And Black Bean Burritos' },
    { id: 4747, name: 'Hasselback Butternut Squash' },
    { id: 4748, name: 'Brownie Truffle-Stuffed Strawberries' },
    { id: 4749, name: 'Sweet Sesame Dumplings (Tangyuan)' },
    { id: 4750, name: 'Candied Sweet Potatoes (Basi Digua)' },
    { id: 4751, name: 'Immunity Boosting Green Soup' },
    { id: 4752, name: 'Classic Pork Dumplings As Made By Yidi Li' },
    { id: 4754, name: 'Steamed Whole Fish With Fresh Ginger' },
    { id: 4755, name: 'Kickstarter Fire Avocado Toast (Aries)' },
    { id: 4756, name: 'Smoked Salmon Avocado Toast (Taurus)' },
    { id: 4757, name: 'Two-Faced Avocado Toast (Gemini)' },
    { id: 4758, name: 'Heart-Shaped Avocado Toast (Cancer)' },
    { id: 4759, name: 'Avocado Rose Toast (Leo)' },
    { id: 4760, name: 'Tenable Avocado Toast (Virgo)' },
    { id: 4761, name: 'Shareable Avocado Toast (Libra)' },
    { id: 4762, name: 'Multifaceted Avocado Toast (Scorpio)' },
    { id: 4763, name: 'Pack And Go Avocado Toast (Sagittarius)' },
    { id: 4765, name: 'Eccentric Avocado Toast (Aquarius)' },
    { id: 4766, name: 'Fantasy / Reality Toast (Pisces)' },
    { id: 4768, name: 'Easy 3-Ingredient Chocolate Mousse' },
    { id: 4769, name: 'Gourmet 4-Ingredient Chocolate Mousse' },
    { id: 4770, name: 'Chocolate Gravy' },
    {
      id: 4771,
      name: 'Unicorn Cookies As Made By Our Facebook Cookie Contest Winner',
    },
    { id: 4772, name: 'One-Pan Whole Roasted Chicken & Veggies' },
    { id: 4773, name: 'Freezer-Prep Veggie Breakfast Burritos' },
    { id: 4774, name: 'Instant-Pot Whole Herb Chicken' },
    { id: 4775, name: 'Anything-You-Got Curry Soup' },
    { id: 4777, name: 'Dark Chocolate Rice Cereal Treat Hearts' },
    { id: 4778, name: 'Easy Bagel Bite Lunch Ideas For Kids' },
    { id: 4779, name: 'Jollof Risotto With Suya-Spiced Shrimp' },
    { id: 4780, name: 'Cheddar Biscuit Chicken Pot Pie' },
    { id: 4781, name: 'Dark Chocolate Peanut Butter Cups' },
    {
      id: 4782,
      name: 'Skirt Steak With Mustard Sauce As Made By Katano Kasaine',
    },
    { id: 4784, name: 'Instant Pot Lasagna' },
    { id: 4785, name: 'Tabitha Brown’s Healthy Vegan Pizza Bagels' },
    { id: 4786, name: 'Breakfast Sausage Egg Cups' },
    { id: 4787, name: 'Chocolate Berry Charlotte' },
    { id: 4788, name: 'Classic Carrot Cake' },
    { id: 4791, name: 'Power Protein Brownies' },
    { id: 4792, name: 'Marcus Samuelsson’s Tibs' },
    { id: 4794, name: 'Siga Tibs And Ethiopian Salad' },
    { id: 4795, name: 'Cod With Confetti Coconut Rice' },
    { id: 4796, name: 'Peanut Butter, Strawberry, And Banana Quesadilla' },
    { id: 4797, name: 'Chicago Dog' },
    { id: 4798, name: 'Chili Con Queso' },
    { id: 4799, name: 'Mandazi' },
    { id: 4800, name: "Kiano's Potato Bhajias" },
    { id: 4802, name: 'Pizza Nachos ' },
    { id: 4803, name: 'Chocolate Coconut Sheet Cake' },
    {
      id: 4804,
      name: 'Hearty Winter Vegetable Salad With Black Onion Seed Vinaigrette',
    },
    { id: 4805, name: 'Raspberry Chocolate Greek Yogurt Cheesecake' },
    { id: 4806, name: 'Chicken And Wild Rice Soup' },
    { id: 4807, name: 'Hummus, Veggie, And Goat Cheese Sandwich' },
    { id: 4808, name: 'Steak Tacos & Next Day Grain Bowl' },
    { id: 4809, name: 'Strawberry Cotton Candy Champagne Cocktail' },
    { id: 4811, name: 'Vegan Mushroom, Pepper, & Olive Pizza' },
    { id: 4814, name: 'Vegan BBQ Jackfruit Pizza' },
    { id: 4816, name: 'Dairy-Free Chicken Fettuccine Alfredo' },
    { id: 4817, name: 'Vegetarian Pad See Ew' },
    { id: 4818, name: 'Jacket Potato: The Traditional' },
    { id: 4819, name: 'Jacket Potato: The Chip-A-Tron' },
    { id: 4820, name: 'Jacket Potato: The Old Fashioned' },
    { id: 4821, name: 'Jacket Potato: The Spud & Mighty' },
    { id: 4822, name: 'Jacket Potato: The Cowboy Potato' },
    { id: 4823, name: 'Jacket Potato: The Chickpea + Chill' },
    { id: 4824, name: 'Jacket Potato: The Idealist' },
    { id: 4825, name: 'Jacket Potato: The Creative Thinker' },
    { id: 4826, name: 'Jacket Potato: The Pizazz' },
    { id: 4827, name: 'Jacket Potato: The Off-Road S’more' },
    { id: 4828, name: 'Jacket Potato: The Claire' },
    { id: 4829, name: 'Jacket Potato: The Canadian' },
    { id: 4830, name: 'Jacket Potato: The Basic' },
    { id: 4831, name: 'Jacket Potato: The You Extra' },
    { id: 4832, name: 'Jacket Potato: The PSI (Peanut Sprinkle Ice Cream)' },
    { id: 4833, name: 'Jacket Potato: The Extrovert' },
    { id: 4834, name: 'Blackberry Whiskey Lemonade' },
    { id: 4836, name: 'Organic Quinoa Rice Cakes With Mediterranean Chicken' },
    { id: 4837, name: 'Cool Ranch Popcorn' },
    { id: 4838, name: 'Honey Mustard Popcorn' },
    { id: 4839, name: 'Buffalo Popcorn' },
    { id: 4840, name: 'BBQ Popcorn' },
    { id: 4841, name: 'Pineapple Carrot Cake Breakfast Bread' },
    { id: 4842, name: 'Cocoa Crispy Rice Chocolate Hazelnut Mousse Pie' },
    { id: 4846, name: 'Chocolate Banana French Toast Breakfast Bake' },
    { id: 4847, name: 'Cheddar, Sausage, And Egg Breakfast Bake' },
    { id: 4848, name: 'Steak, Egg, And Cheese Breakfast Sandwich' },
    { id: 4849, name: 'Chicken Katsu Sandwiches As Made By Hitomi’s Mom' },
    { id: 4850, name: 'Chicken Fries Poutine' },
    { id: 4851, name: 'Lasagna Skillet Pasta' },
    { id: 4852, name: 'Spring Vegetable Chowder' },
    { id: 4853, name: 'Shredded Teriyaki Chicken Salad' },
    { id: 4854, name: 'Potato Chip–Coated Onion Rings' },
    { id: 4855, name: 'Hash-Brown Waffles' },
    { id: 4856, name: 'Potato Latkes' },
    { id: 4857, name: 'Mango Kiwi Pineapple Sangria' },
    { id: 4858, name: 'Sheet Pan Tofu 3 Ways' },
    { id: 4859, name: 'New York City Dog' },
    { id: 4860, name: 'Los Angeles Dog' },
    { id: 4861, name: 'Memphis Dog' },
    { id: 4862, name: 'Chicken Tagine' },
    { id: 4863, name: 'Tofu Buddha Bowl' },
    { id: 4864, name: 'Fiery Fries' },
    { id: 4865, name: 'Potato Bake Side Meal Prep' },
    { id: 4866, name: 'Hearty Onion Dip And Chips' },
    { id: 4867, name: 'Hearty Turkey Tacos' },
    { id: 4868, name: 'Jazzy Shrimp And Grits' },
    { id: 4869, name: 'Zesty One-Pot Chicken Bake' },
    { id: 4870, name: 'Creamy Cajun Pasta' },
    { id: 4872, name: 'Savoury Cheese Crackers' },
    { id: 4873, name: 'Savoury White Fish With Simmered Tomatoes' },
    { id: 4874, name: 'Fiery Chicken Wings' },
    { id: 4876, name: 'Seafood Casserole As Made By Betsy’s Gammy' },
    { id: 4877, name: 'Chicken Cotoletta As Made By Anna O’Halloran' },
    { id: 4878, name: 'Chicken Parmesan As Made By Chris Nasatrini' },
    { id: 4879, name: 'Tofu Bowl' },
    { id: 4880, name: 'Hearty Roast Chicken' },
    { id: 4881, name: 'Hearty Lamb Chops With Couscous' },
    {
      id: 4882,
      name: 'Zesty Tomato Bruschetta 2 Ways: Fresh And Oven-Roasted',
    },
    { id: 4883, name: 'Zesty Halibut And Green Beans' },
    { id: 4884, name: 'Zesty Chicken Skewers With Yogurt Dip' },
    { id: 4886, name: 'Savoury Spaghetti With Meatballs' },
    { id: 4887, name: 'Roasted Tomato Soup And Grilled Cheese' },
    { id: 4888, name: 'Fiery Chicken And Rice Noodles' },
    { id: 4890, name: 'Jazzy Hush Puppies' },
    { id: 4891, name: 'Jazzy Steak Salad' },
    { id: 4892, name: 'Jazzy Fried Chicken' },
    { id: 4893, name: 'Blood Orange Chocolate Olive Oil Cake' },
    { id: 4000, name: 'Veggie-Packed Chow Mein' },
    { id: 4001, name: 'Beef & Broccoli Chow Mein' },
    { id: 4002, name: 'The Ultimate Breakfast Corndog' },
    { id: 4007, name: 'Classic Hummus By Alon Shaya' },
    { id: 4008, name: 'Grilled Cheese Sloppy Joe Cups' },
    { id: 4011, name: 'Cioppino (Seafood Tomato Stew)' },
    { id: 4012, name: 'Beetroot & Feta Burgers' },
    { id: 4013, name: 'Bibimbap By Chef Esther Choi' },
    { id: 4014, name: 'Salted, Malted Cookie Dough Ice Cream By Salt & Straw' },
    { id: 4015, name: 'Chinese Chicken Curry' },
    { id: 4016, name: 'Chicken Teriyaki Crispy Noodle Bowl' },
    { id: 4017, name: 'Cornbread Crab Cakes By Lawrence Page' },
    { id: 4018, name: 'Steak And Potato Taco Nachos' },
    { id: 4019, name: 'Habanero Hot Sauce' },
    { id: 4020, name: 'Jalapeño Mild Sauce' },
    { id: 4021, name: 'Baked Salt And Pepper Wings' },
    { id: 4024, name: 'Bacon Cheddar Jalapeño-Stuffed Hush Puppies' },
    { id: 4025, name: 'Rosé Gummy Bears' },
    { id: 4026, name: 'Grilled Cheese' },
    { id: 4027, name: 'White Rice' },
    { id: 4028, name: 'Buttermilk Pancakes' },
    { id: 4029, name: 'Whipped Cream' },
    { id: 4030, name: 'Simple Scrambled Eggs' },
    { id: 4031, name: 'Audrey Hepburn’s Spaghetti Al Pomodoro' },
    { id: 4033, name: 'Chili Cheese Burger Bowls' },
    { id: 4034, name: 'Ham And Cheese Hash Brown Cubes' },
    { id: 4035, name: "Ice Cream 'Box' Cake Pops" },
    { id: 4036, name: 'Fried Rice Chicken Teriyaki Cups' },
    { id: 4039, name: 'Penne With Tomato Sauce' },
    { id: 4040, name: 'Spaghetti With Garlic And Oil' },
    { id: 4041, name: 'Tuna Linguine With Tomatoes, Olives, and Capers' },
    { id: 4042, name: 'Cacio e Pepe (Spaghetti with Cheese and Pepper)' },
    { id: 4043, name: 'Crispy Chicken Teriyaki Rice Balls' },
    { id: 4044, name: 'Dairy-Free Peach Tart' },
    { id: 4045, name: 'Chicken Gyro Sliders' },
    { id: 4046, name: 'Rainbow Sheet-Pan Pizza' },
    { id: 4047, name: 'Short Rib Ragù' },
    { id: 4048, name: 'Chocolate Cookie Cheesecake-Stuffed Brownies' },
    { id: 4049, name: 'Arroz Con Pollo With Matt And Patrick' },
    { id: 4050, name: 'Anti-Inflammatory Golden Milk' },
    { id: 4051, name: 'Rainbow Swirl Meringues' },
    { id: 4053, name: 'Rainbow Hummus' },
    { id: 4056, name: 'Nourishing Rainbow Protein Pot' },
    { id: 4057, name: 'Potato Flower Breakfast Cups' },
    { id: 4061, name: 'Chilaquiles With Andrea Mares' },
    { id: 4062, name: 'Veggie Hummus Trio' },
    { id: 4063, name: 'Cucumber Rolls' },
    { id: 4064, name: 'Pesto Turkey Pinwheels' },
    { id: 4065, name: 'Cookie Fruit Pizzas' },
    { id: 4066, name: 'Tater Tot Quiche' },
    { id: 4068, name: 'Strawberries And Cream Soufflé' },
    { id: 4069, name: 'Vanilla Black Tea Smoothie' },
    { id: 4070, name: 'Banana Matcha Smoothie' },
    { id: 4071, name: 'Cinnamon Coffee Smoothie' },
    { id: 4072, name: 'Avocado Cold Brew Smoothie' },
    { id: 4073, name: 'Giant Multi-Stuffed Soft Pretzel' },
    { id: 4074, name: 'Chocolate Banana Crepe Tower' },
    { id: 4075, name: 'Cinnamon Polka Dot Crepes' },
    { id: 4076, name: 'Strawberry Crepe Hearts' },
    { id: 4077, name: 'Pb&j Crepe Gift Box' },
    {
      id: 4078,
      name: 'Pollo Ciudad With Cilantro Sauce And Pickled Tomato Salsa',
    },
    { id: 4079, name: 'Roasted Veggie Summer Salad' },
    { id: 4080, name: 'Molten Churro Bombs' },
    { id: 4081, name: 'Meatball Lasagna Bombs' },
    { id: 4083, name: 'Grilled Salmon' },
    { id: 4084, name: 'Crab Cakes' },
    { id: 4085, name: 'Lobster Roll' },
    { id: 4086, name: 'Seared Scallops' },
    {
      id: 4087,
      name: 'Homemade Chicken Shawarma With Ben Stiller And Ahmed Badr',
    },
    { id: 4088, name: 'Tuna Salad With Roasted Veggies' },
    { id: 4089, name: 'Sun-Dried Tomato & Spinach Tuna Pasta' },
    { id: 4090, name: 'Tuna Burgers' },
    { id: 4091, name: 'Rainbow Veggie And Pesto Tart' },
    { id: 4093, name: 'Chocolate Peanut Butter Cake In A Jar' },
    { id: 4094, name: 'Strawberries And Cream Cake In A Jar' },
    { id: 4095, name: 'Cookies And Cream Cake In A Jar' },
    { id: 4096, name: 'Birthday Cake In A Jar' },
    { id: 4098, name: 'Pesto Garden Pasta For The Whole Family' },
    { id: 4099, name: 'Watermelon Lime Sangria Ice Pops' },
    { id: 4100, name: 'Raspberry Mango Sangria Ice Pops' },
    { id: 4101, name: 'Strawberry Kiwi Sangria Ice Pops' },
    { id: 4102, name: 'Classic Sangria Ice Pops' },
    { id: 4103, name: 'Ice Cream Sandwich Swirl Cake' },
    { id: 4105, name: 'The Best Ever Vegan Brownies' },
    { id: 4106, name: 'Coleslaw' },
    { id: 4108, name: 'BBQ Chicken Sandwich' },
    { id: 4109, name: 'Rustic Potato Salad' },
    { id: 4110, name: 'Strawberry Shortcake' },
    { id: 4111, name: "Marbled 4th Of July 'Box' Cake" },
    { id: 4112, name: 'Tortilla Bowl Southwestern Salad' },
    { id: 4113, name: 'Mixed Gravy Poutine' },
    { id: 4114, name: 'Tomato Gazpacho' },
    { id: 4115, name: 'Watermelon Gazpacho' },
    { id: 4116, name: 'Mango Gazpacho' },
    { id: 4117, name: 'Vegan Strawberry Shortcake Pops' },
    { id: 4118, name: 'Healthier Key Lime Bars' },
    { id: 4119, name: 'Meatless Sloppy Joes' },
    { id: 4120, name: 'Fruit Spring Rolls With Strawberry Lemonade Dip' },
    { id: 4121, name: 'Veggie Spring Rolls With Peanut Sauce' },
    { id: 4122, name: 'Pesto And Prosciutto Zucchini Linguine' },
  ];

  ingredients = [
    'vegetable stock',
    'star anise pod',
    'potato',
    'sauerkraut',
    'chives',
    'serrano chile',
    'candied ginger',
    'whole chicken',
    'crouton',
    'lemon zest',
    'small avocado',
    'ice',
    'shredded carrot',
    'ground lamb',
    'olive oil',
    'coriander',
    'fried egg',
    'ancho chilies',
    'chai tea',
    'star anise',
    'small jalapeño',
    'evaporated milk',
    'raspberry jam',
    'vegetable broth',
    'flour tortilla',
    'jackfruit',
    'boiling water',
    'sesame oil',
    'dried rosemary',
    'pizza sauce',
    'whole milk',
    'egg noodle',
    'pumpkin puree',
    'small red onion',
    'wooden skewer',
    'black olive',
    'sweet mirin',
    'pork chorizo',
    'large carrots',
    'vanilla',
    'anchovies',
    'chicken stock',
    'refried beans',
    'red potato',
    'mango',
    'diced celery',
    'agave nectar',
    'blueberries',
    'cucumber',
    'orange',
    'russet potatoes',
    'corn chips',
    'curry paste',
    'cornflour',
    'grapefruit',
    'dark rum',
    'corn tortilla',
    'toasted pecans',
    'chili powder',
    'iceberg lettuce',
    'paprika',
    'white rum',
    'salted butter',
    'white onion',
    'fresh rosemary',
    'oranges',
    'roasted peanuts',
    'lasagna noodle',
    'fresh oregano',
    'pitted date',
    'ghee',
    'beef stock',
    'bosc pear',
    'red radishes',
    'yellow onion',
    'scallions',
    'black pepper',
    'pico de gallo',
    'flour',
    'ripe banana',
    'large carrot',
    'diced tomatoes',
    'eggnog',
    'linguine',
    'mixed berries',
    'flank steak',
    'watermelon',
    'club soda',
    'grenadine',
    'canola oil',
    'agar agar',
    'cold water',
    'pesto sauce',
    'large lemon',
    'fine salt',
    'tuscan kale',
    'rum',
    'pistachio',
    'fine sugar',
    'leftover peas',
    'ground pepper',
    'pepper',
    'buckwheat flour',
    'large eggplant',
    'onion bagels',
    'dry mustard',
    'oil',
    'manila clam',
    'avocado',
    'caster sugar',
    'garlic cloves',
    'sanding sugar',
    'garam masala',
    'mirin',
    'hoisin sauce',
    'purple potato',
    'savoy cabbage',
    'ground cloves',
    'baking soda',
    'chipotle powder',
    'matcha powder',
    'coconut sugar',
    'maple syrup',
    'long grain rice',
    'graham cracker',
    'ground pork',
    'piloncillo',
    'yellow cake mix',
    'icing',
    'black tea',
    'green onions',
    'prosciutto',
    'ginger',
    'dough',
    'cooking oil',
    'red pepper',
    'garlic granules',
    'black beans',
    'pinto bean',
    'tahini',
    'dark soy sauce',
    'fine sea salt',
    'vegetable oil',
    'zucchini',
    'pork sausage',
    'dried cherry',
    'banana',
    'grape tomatoes',
    'sundried tomato',
    'lime wedge',
    'large egg yolk',
    'vegan butter',
    'large red onion',
    'lemon wedges',
    'spice blend',
    'instant yeast',
    'cooked bacon',
    'pepitas',
    'plain flour',
    'medium leek',
    'apple juice',
    'skirt steak',
    'swiss cheese',
    'delicata squash',
    'small apple',
    'american cheese',
    'dried sage',
    'lemongrass',
    'chicken',
    'white cake mix',
    'sesame seed',
    'simple syrup',
    'medium eggplant',
    'fresh blueberry',
    'raisins',
    'tuna',
    'red cabbage',
    'flaxseed',
    'sliced onion',
    'strawberry',
    'chuck roast',
    'gala apple',
    'raw shrimp',
    'buttermilk',
    'raspberry',
    'cumin',
    'cod fillets',
    'carrots',
    'deli turkey',
    'fried onion',
    'fresh basil',
    'edible flower',
    'cooked quinoa',
    'red grapes',
    'cinnamon',
    'pumpkin',
    'sriracha',
    'queso',
    'soda water',
    'baby potato',
    'grapes',
    'serrano pepper',
    'dried apricot',
    'stuffing mix',
    'garlic powder',
    'chicken thighs',
    'warm milk',
    'caramel candy',
    'flaky sea salt',
    'small pumpkin',
    'roma tomato',
    'hard-boiled egg',
    'fresh berries',
    'bacon',
    'cheddar cheese',
    'tomato',
    'cornmeal',
    'mayonnaise',
    'yellow cornmeal',
    'lacinato kale',
    'swiss chard',
    'extra-firm tofu',
    'blackberry',
    'spiced rum',
    'crab meat',
    'walnut',
    'mixed greens',
    'bread flour',
    'milk of choice',
    'squid',
    'dark chocolate',
    'feta cheese',
    'hibiscus flower',
    'sandwich cookie',
    'beetroot',
    'fresh mint',
    'deli ham',
    'baguette',
    'golden raisin',
    'cardamom pods',
    'double cream',
    'large shallot',
    'red curry paste',
    'fresh chives',
    'bread crumbs',
    'hamburger bun',
    'fresh ginger',
    'sesame seeds',
    'coconut cream',
    'milk',
    'hot dog bun',
    'bean sprout',
    'leftover turkey',
    'earl grey tea',
    'agave',
    'mustard powder',
    'cherry pepper',
    'capers in brine',
    'oats',
    'lemon',
    'yellow squash',
    'lime wedges',
    'allspice',
    'sour cream',
    'rice noodle',
    'pumpkin seeds',
    'injera',
    'raisin',
    'rice flour',
    'fresh parsley',
    'sour mix',
    'organic sugar',
    'vodka',
    'halibut fillet',
    'cane sugar',
    'dried currants',
    'large avocado',
    'vanilla essense',
    'white bread',
    'rosé wine',
    'kalamata olive',
    'sandwich bread',
    'chickpeas',
    'clove',
    'dried oregano',
    'tomato sauce',
    'pita chip',
    'glazed fruit',
    'raw pepitas',
    'diced red onion',
    'brown rice',
    'lemon extract',
    'medium tomato',
    'puff pastry',
    'breadcrumb',
    'dried fig',
    'medium cucumber',
    'celery stalk',
    'medium zucchini',
    'frozen cherry',
    'smoked salmon',
    'broccolini',
    'nigella seed',
    'hazelnut',
    'vegan stuffing',
    'dried cherries',
    'yerba mate',
    'dry red wine',
    'spanish olive',
    'sugar',
    'fresh scallion',
    'grape tomato',
    'coriander seeds',
    'blue frosting',
    'broccoli rabe',
    'poppy seed bun',
    'medium carrots',
    'red onion',
    'rice vinegar',
    'pork tenderloin',
    'creamed corn',
    'lime leaves',
    'marshmallow',
    'roma tomatoes',
    'salt',
    'raw walnuts',
    'orange segments',
    'whole clove',
    'pesto',
    'biscuit',
    'granola',
    'lemon juice',
    'daikon radish',
    'rosé',
    'lime juice',
    'kidney bean',
    'eggs',
    'chickpea flour',
    'curry powder',
    'eggplant',
    'baby spinach',
    'sweet potatoes',
    'corn oil',
    'ground cinnamon',
    'ground ginger',
    'hard red candy',
    'nutmeg',
    'hemp hearts',
    'peas',
    'raw walnut',
    'chiles de árbol',
    'artichoke heart',
    'red bean paste',
    'raw cashews',
    'barbecue sauce',
    'apple',
    'pear',
    'plain yogurt',
    'onion',
    'sliced almonds',
    'mushroom blend',
    'avocado crema',
    'peanut brittle',
    'brie cheese',
    'red kidney bean',
    'pizza dough',
    'coconut oil',
    'hazelnuts',
    'whole wheat',
    'ground allspice',
    'walnuts',
    'potato chips',
    'ricotta cheese',
    'pine nuts',
    'bread',
    'coffee',
    'pancetta',
    'medium carrot',
    'fresh sage',
    'green apple',
    'fresh cilantro',
    'ground cumin',
    'roasted peanut',
    'pineapple',
    'saffron thread',
    'coffee bean',
    'lemonade',
    'sweet potato',
    'strawberry jam',
    'gin',
    'dry white wine',
    'cherry tomato',
    'ground turmeric',
    'sofrito',
    'pitted prunes',
    'sirloin steak',
    'hot sauce',
    'dried parsley',
    'silken tofu',
    'tonic water',
    'low-carb bread',
    'applesauce',
    'chopped cabbage',
    'elbow macaroni',
    'arepa flour',
    'celery salt',
    'large orange',
    'black tea bag',
    'rib eye steak',
    'vegan chocolate',
    'carrot',
    'farro',
    'oat flour',
    'shrimp',
    'ranch dressing',
    'berbere',
    'lime zest',
    'crushed tomato',
    'minced garlic',
    'fish stock',
    'jalapeños',
    'cornstarch',
    'chocolate syrup',
    'kosher salt',
    'diced tomato',
    'coarse sugar',
    'arborio rice',
    'beef broth',
    'leftover gravy',
    'flakey sea salt',
    'non-dairy milk',
    'parsnip',
    'condensed milk',
    'tartar sauce',
    'molasses',
    'miso paste',
    'parmesan cheese',
    'light soy sauce',
    'kale',
    'potato starch',
    'small onion',
    'rice',
    'chicken broth',
    'vanilla extract',
    'tahini paste',
    'buffalo sauce',
    'large onion',
    'guajillo chiles',
    'cream cheese',
    'bbq sauce',
    'rye whiskey',
    'large cucumber',
    'small zucchini',
    'fresh egg white',
    'mini pepperoni',
    'celery',
    'jalapeño',
    'red chili',
    'sweet red wine',
    'cinnamon stick',
    'spaghetti',
    'pickled ginger',
    'large scallops',
    'pumpkin spice',
    'guacamole',
    'turkey stock',
    'snap peas',
    'asparagus',
    'ground chicken',
    'lemon wedge',
    'chips',
    'pork shoulder',
    'lemon-lime soda',
    'greek yogurt',
    'leeks',
    'date',
    'canned chickpea',
    'filtered water',
    'orange liqueur',
    'spiced butter',
    'tomatillo',
    'cayenne',
    'dried basil',
    'slivered almond',
    'sport peppers',
    'acorn squash',
    'cherry brandy',
    'dried thyme',
    'fresh herbs',
    'herb salt',
    'turmeric',
    'ground nutmeg',
    'almond milk',
    'pumpkin brittle',
    'rosehip',
    'pretzel buns',
    'small mango',
    'habanero pepper',
    'uncooked farro',
    'sliced tomato',
    'red wine',
    'fresh mint leaf',
    'white mushroom',
    'dry sherry',
    'gochujang',
    'cooking spray',
    'white chocolate',
    'fresh herb',
    'almond extract',
    'mushroom',
    'large tomato',
    'mesclun greens',
    'red apple',
    'vanilla bean',
    'fresh arugula',
    'cranberry sauce',
    'beef broth cube',
    'green cabbage',
    'queso dip',
    'small beet',
    'sliced almond',
    'sliced radishes',
    'fish sauce',
    'bagel',
    'white fondant',
    'ice water',
    'cheese sauce',
    'tequila',
    'chilli powder',
    'corn syrup',
    'medium beet',
    'fresh dill',
    'cheese',
    'sourdough bread',
    'dried chickpeas',
    'dried spathetti',
    'dried cranberry',
    'beef tenderloin',
    'salmon fillet',
    'pineapple juice',
    'smoked paprika',
    'green onion',
    'coconut rum',
    'marinara sauce',
    'quick oat',
    'french bread',
    'curly kale',
    'baking powder',
    'sticky rice',
    'ribeye steak',
    'cornflakes',
    'russet potato',
    'whipped topping',
    'shredded cheese',
    'white rice',
    'chocolate chips',
    'corn',
    'sea salt',
    'cocoa powder',
    'egg wash',
    'white wine',
    'oil of choice',
    'icing sugar',
    'soy sauce',
    'fresh coriander',
    'garlic paste',
    'cashew milk',
    'thick-cut bacon',
    'yellow mustard',
    'brown sugar',
    'sprinkles',
    'beef hot dog',
    'leek',
    'chili paste',
    'chopped walnuts',
    'spinach',
    'pearl onion',
    'radish',
    'mussel',
    'heavy cream',
    'poblano pepper',
    'ginger beer',
    'ground flaxseed',
    'bell pepper',
    'plum',
    'brussel sprout',
    'rack of lamb',
    'rice cereal',
    'mashed potatoes',
    'large egg',
    'fennel seeds',
    'hot dog',
    'corn kernels',
    'purple cabbage',
    'raw tahini',
    'coleslaw',
    'mixed fruit',
    'kiwi',
    'triple sec',
    'coconut milk',
    'warm water',
    'honey',
    'full-fat yogurt',
    'gravy',
    'powdered sugar',
    'green pepper',
    'hibiscus tea',
    'sausage patty',
    'quinoa',
    'caper',
    'small shallot',
    'neutral oil',
    'tamarind paste',
    'recaito',
    'extra firm tofu',
    'pastry flour',
    'dairy-free milk',
    'chopped onions',
    'whipped cream',
    'medium onion',
    'fresh raspberry',
    'italian sausage',
    'yucca',
    'medium jalapeno',
    'ice cream',
    'bay leaf',
    'fresh shrimp',
    'milk powder',
    'hard blue candy',
    'chopped lettuce',
    'seltzer water',
    'orange peel',
    'fresh thyme',
    'pasilla chile',
    'diced jalapeños',
    'corn starch',
    'ginger paste',
    'wild rice',
    'ripe pear',
    'francese roll',
    'flax seed',
    'turnip',
    'rice wine',
    'egg',
    'baby carrots',
    'cream of tartar',
    'fresh spinach',
    'ground beef',
    'annatto paste',
    'mustard',
    'medium shallot',
    'ketchup',
    'green beans',
    'candy cane',
    'beet',
    'stale bread',
    'thai tea',
    'large eggs',
    'champagne',
    'brioche bread',
    'red frosting',
    'small potato',
    'ground cardamom',
    'butter',
    'glass noodle',
    'lasagna noodles',
    'large shrimp',
    'blueberry',
    'broccoli floret',
    'turkey',
    'collard green',
    'galangal',
    'dijon mustard',
    'kimchi',
    'polenta',
    'pepperoni slice',
    'snow peas',
    'almond flour',
    'lime',
    'blood orange',
    'red sprinkles',
    'mushrooms',
    'sliced avocado',
    'basmati rice',
    'chia seeds',
    'lobster meat',
    'water',
    'chestnut',
    'honey syrup',
    'bean sprouts',
    'diced carrots',
    'pancake mix',
    'xanthan gum',
    'liquid smoke',
    'toasted pepitas',
    'onion powder',
    'brandy',
    'vanilla yogurt',
    'orange zest',
    'ham',
    'dried bay leaf',
    'chopped pecan',
    'button mushroom',
    'pork lard',
    'scallion',
    'half & half',
    'corn kernel',
    'sugar cookie',
    'prime rib',
    'fresh parlsey',
    'broccoli',
    'queso fresco',
    'frozen spinach',
    'tomato paste',
    'flaxseed meal',
    'milk or stock',
    'almond',
    'unsalted butter',
    'cinnamon sugar',
    'shallot',
    'coarse salt',
    'chicken breast',
    'apple cider',
    'chicken wings',
    'salsa',
    'cayenne pepper',
    'almond meal',
    'white vinegar',
    'whiskey',
    'ramen noodle',
    'coconut flakes',
    'medium egg',
    'orange juice',
    'sea scallop',
    'goat cheese',
    'sushi rice',
    'hot water',
    'cherry tomatoes',
    'penne pasta',
    'cheese curd',
    'plantain',
    'almond butter',
    'garlic',
    'melted butter',
    'ricotta salata',
    'hummus',
    'espresso beans',
    'peanut butter',
    'red bell pepper',
    'rolled oats',
    'white pepper',
    'bijol seasoning',
    'cotton candy',
    'cashews',
    'herb sea salt',
    'cauliflower',
  ];

  getRecipeNames() {
    return this.recipes.map((recipe) => recipe.name);
  }

  getIngredientName() {
    return this.ingredients;
  }

  getRecipeByName(name: string) {
    return this.recipes.find((recipe) => recipe.name === name);
  }
}
